/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class NPG extends javax.swing.JFrame {

    /**
     * Creates new form NPG
     */
    ArrayList<JButton> button;
    int labelIndex = 0;

    public NPG() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        makeNewGame();
    }

    private void makeNewGame() {
        button = new ArrayList<>();
        button.add(btn1);
        button.add(btn2);
        button.add(btn3);
        button.add(btn4);
        button.add(btn5);
        button.add(btn6);
        button.add(btn7);
        button.add(btn8);
        button.add(btn9);
        Random rd = new Random();
        int key;
        ArrayList<Integer> labelList;
        do {
            key = 0;
            labelList = new ArrayList<>();
            for (int i = 0; i < 9; i++) {
                labelIndex = rd.nextInt(9);
                while (labelList.contains(labelIndex)) {
                    labelIndex = rd.nextInt(9);
                }
                labelList.add(labelIndex);
            }
            for (int i = 0; i < 8; i++) {
                for (int j = i + 1; j < 9; j++) {
                    if (labelList.get(i) > labelList.get(j) && labelList.get(j) != 0) {
                        key++;
                    }
                }
            }
        } while (key % 2 != 0);
        for (int i = 0; i < 9; i++) {
            button.get(i).setText((labelList.get(i) == 0) ? "" : labelList.get(i) + "");
        }
    }

    private boolean checkWin() {
        if ("".equals(btn9.getText())) {
            for (int i = 1; i < 9; i++) {
                String temp = i + "";
                if (!temp.equals(button.get(i - 1).getText())) {
                    return false;
                }
            }
        } else {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn3x3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setPreferredSize(new java.awt.Dimension(60, 60));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setPreferredSize(new java.awt.Dimension(60, 60));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setPreferredSize(new java.awt.Dimension(60, 60));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setPreferredSize(new java.awt.Dimension(60, 60));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setPreferredSize(new java.awt.Dimension(60, 60));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setPreferredSize(new java.awt.Dimension(60, 60));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setPreferredSize(new java.awt.Dimension(60, 60));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setPreferredSize(new java.awt.Dimension(60, 60));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setPreferredSize(new java.awt.Dimension(60, 60));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn3x3Layout = new javax.swing.GroupLayout(pn3x3);
        pn3x3.setLayout(pn3x3Layout);
        pn3x3Layout.setHorizontalGroup(
            pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn3x3Layout.setVerticalGroup(
            pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnNewGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn1.getText());
            btn1.setText("");
        }
        if (btn4.getText() == "") {
            btn4.setText(btn1.getText());
            btn1.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        makeNewGame();
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText() == "") {
            btn1.setText(btn2.getText());
            btn2.setText("");
        }
        if (btn3.getText() == "") {
            btn3.setText(btn2.getText());
            btn2.setText("");
        }
        if (btn5.getText() == "") {
            btn5.setText(btn2.getText());
            btn2.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn3.getText());
            btn3.setText("");
        }
        if (btn6.getText() == "") {
            btn6.setText(btn3.getText());
            btn3.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (btn4.getText() == "") {
            btn4.setText(btn7.getText());
            btn7.setText("");
        }
        if (btn8.getText() == "") {
            btn8.setText(btn7.getText());
            btn7.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (btn6.getText() == "") {
            btn6.setText(btn9.getText());
            btn9.setText("");
        }
        if (btn8.getText() == "") {
            btn8.setText(btn9.getText());
            btn9.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText() == "") {
            btn1.setText(btn4.getText());
            btn4.setText("");
        }
        if (btn5.getText() == "") {
            btn5.setText(btn4.getText());
            btn4.setText("");
        }
        if (btn7.getText() == "") {
            btn7.setText(btn4.getText());
            btn4.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText() == "") {
            btn3.setText(btn6.getText());
            btn6.setText("");
        }
        if (btn5.getText() == "") {
            btn5.setText(btn6.getText());
            btn6.setText("");
        }
        if (btn9.getText() == "") {
            btn9.setText(btn6.getText());
            btn6.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (btn5.getText() == "") {
            btn5.setText(btn8.getText());
            btn8.setText("");
        }
        if (btn7.getText() == "") {
            btn7.setText(btn8.getText());
            btn8.setText("");
        }
        if (btn9.getText() == "") {
            btn9.setText(btn8.getText());
            btn8.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn5.getText());
            btn5.setText("");
        }
        if (btn4.getText() == "") {
            btn4.setText(btn5.getText());
            btn5.setText("");
        }
        if (btn6.getText() == "") {
            btn6.setText(btn5.getText());
            btn5.setText("");
        }
        if (btn8.getText() == "") {
            btn8.setText(btn5.getText());
            btn5.setText("");
        }
        if (checkWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NPG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JPanel pn3x3;
    // End of variables declaration//GEN-END:variables
}
