/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class Picture extends javax.swing.JFrame {

    /**
     * Creates new form Picture
     */
    int flag;

    public Picture() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setImage(btnImg1, "/1.jpg", 60, 60);
        setImage(btnImg2, "/2.jpg", 60, 60);
        setImage(btnImg3, "/3.jpg", 60, 60);
        setImage(btnImg4, "/4.jpg", 60, 60);
        setImage(btnImg5, "/5.jpg", 60, 60);
    }

    public void setImage(JButton btn, String url, int width, int height) {
        ImageIcon icon = new ImageIcon(this.getClass().getResource(url));
        Image img = icon.getImage();
        img = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        btn.setIcon(icon);
    }

    public void setLabel(JLabel label, String url, int width, int height) {
        ImageIcon icon = new ImageIcon(this.getClass().getResource(url));
        Image img = icon.getImage();
        img = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        icon = new ImageIcon(img);
        label.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImg1 = new javax.swing.JButton();
        btnImg2 = new javax.swing.JButton();
        btnImg3 = new javax.swing.JButton();
        btnImg4 = new javax.swing.JButton();
        btnImg5 = new javax.swing.JButton();
        lbPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        btnImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg1ActionPerformed(evt);
            }
        });

        btnImg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg2ActionPerformed(evt);
            }
        });

        btnImg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg3ActionPerformed(evt);
            }
        });

        btnImg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg4ActionPerformed(evt);
            }
        });

        btnImg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImg5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImg5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImg4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnImg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImg2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg1ActionPerformed
        // TODO add your handling code here:
        setLabel(lbPicture, "/1.jpg", lbPicture.getWidth(), lbPicture.getHeight());
        flag = 1;
    }//GEN-LAST:event_btnImg1ActionPerformed

    private void btnImg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg2ActionPerformed
        // TODO add your handling code here:
        setLabel(lbPicture, "/2.jpg", lbPicture.getWidth(), lbPicture.getHeight());
        flag = 2;
    }//GEN-LAST:event_btnImg2ActionPerformed

    private void btnImg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg3ActionPerformed
        // TODO add your handling code here:
        setLabel(lbPicture, "/3.jpg", lbPicture.getWidth(), lbPicture.getHeight());
        flag = 3;
    }//GEN-LAST:event_btnImg3ActionPerformed

    private void btnImg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg4ActionPerformed
        // TODO add your handling code here:
        setLabel(lbPicture, "/4.jpg", lbPicture.getWidth(), lbPicture.getHeight());
        flag = 4;
    }//GEN-LAST:event_btnImg4ActionPerformed

    private void btnImg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImg5ActionPerformed
        // TODO add your handling code here:
        setLabel(lbPicture, "/5.jpg", lbPicture.getWidth(), lbPicture.getHeight());
        flag = 5;
    }//GEN-LAST:event_btnImg5ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        if (flag == 1) {
            setLabel(lbPicture, "/1.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
        }
        if (flag == 2) {
            setLabel(lbPicture, "/2.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
        }
        if (flag == 3) {
            setLabel(lbPicture, "/3.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
        }
        if (flag == 4) {
            setLabel(lbPicture, "/4.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
        }
        if (flag == 5) {
            setLabel(lbPicture, "/5.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
        }
    }//GEN-LAST:event_formWindowStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        if (flag == 1) {
            setLabel(lbPicture, "/1.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
            lbPicture.setSize(this.getWidth(), this.getHeight() - 100);
        }
        if (flag == 2) {
            setLabel(lbPicture, "/2.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
            lbPicture.setSize(this.getWidth(), this.getHeight() - 100);
        }
        if (flag == 3) {
            setLabel(lbPicture, "/3.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
            lbPicture.setSize(this.getWidth(), this.getHeight() - 100);
        }
        if (flag == 4) {
            setLabel(lbPicture, "/4.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
            lbPicture.setSize(this.getWidth(), this.getHeight() - 100);
        }
        if (flag == 5) {
            setLabel(lbPicture, "/5.jpg", lbPicture.getWidth(), lbPicture.getHeight() - 120);
            lbPicture.setSize(this.getWidth(), this.getHeight() - 100);
        }
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Picture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImg1;
    private javax.swing.JButton btnImg2;
    private javax.swing.JButton btnImg3;
    private javax.swing.JButton btnImg4;
    private javax.swing.JButton btnImg5;
    private javax.swing.JLabel lbPicture;
    // End of variables declaration//GEN-END:variables
}
