/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class NPG2 extends javax.swing.JFrame {

    /**
     * Creates new form NPG
     */
    ArrayList<JButton> button;
    int labelIndex = 0, moveCount = 1;
    Timer time;
    int count = 0;

    public NPG2() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        makeNewGame();
        countUpTime();
    }

    private void countUpTime() {
        time = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (validWin()) {
                    time.stop();
                }
                count++;
                if (count < 1000000000) {
                    lbElapsed.setText(Integer.toString(count) + " sec");
                } else {
                    ((Timer) (e.getSource())).stop();
                }
            }
        });
        time.setInitialDelay(0);
        time.start();
    }

    private void makeNewGame() {
        button = new ArrayList<>();
        button.add(btn1);
        button.add(btn2);
        button.add(btn3);
        button.add(btn4);
        button.add(btn5);
        button.add(btn6);
        button.add(btn7);
        button.add(btn8);
        button.add(btn9);
        button.add(btn10);
        button.add(btn11);
        button.add(btn12);
        button.add(btn13);
        button.add(btn14);
        button.add(btn15);
        button.add(btn16);
        Random rd = new Random();
        int key;
        int emptyIndex;
        boolean valid;
        ArrayList<Integer> labelList;
        do {
            key = 0;
            emptyIndex = 0;
            valid = false;
            labelList = new ArrayList<>();
            for (int i = 0; i < 16; i++) {
                labelIndex = rd.nextInt(16);
                while (labelList.contains(labelIndex)) {
                    labelIndex = rd.nextInt(16);
                }
                labelList.add(labelIndex);
            }
            for (int i = 0; i < 15; i++) {
                for (int j = i + 1; j < 16; j++) {
                    if (labelList.get(i) == 0) {
                        emptyIndex = i + 1;
                    }
                    if (labelList.get(i) > labelList.get(j) && labelList.get(j) != 0) {
                        key++;
                    }
                }
            }
            if ((key % 2 == 0 && emptyIndex % 2 == 0) || (key % 2 != 0 && emptyIndex % 2 != 0)) {
                valid = true;
            }
        } while (!valid);
        for (int i = 0; i < 16; i++) {
            button.get(i).setText((labelList.get(i) == 0) ? "" : labelList.get(i) + "");
        }
        moveCount = 1;
        lbMoveCount.setText("0");
        count = 0;
        lbElapsed.setText("0 sec");
    }

    private boolean validWin() {
        if ("".equals(btn16.getText())) {
            for (int i = 1; i < 16; i++) {
                String temp = i + "";
                System.out.println(temp + "   " + button.get(i - 1).getText());
                if (!temp.equals(button.get(i - 1).getText())) {
                    return false;
                }
            }
        } else {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unvalided")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn3x3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btnNewGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        lbMoveCount = new javax.swing.JLabel();
        lbElapsed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setPreferredSize(new java.awt.Dimension(60, 60));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setPreferredSize(new java.awt.Dimension(60, 60));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setPreferredSize(new java.awt.Dimension(60, 60));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn5.setPreferredSize(new java.awt.Dimension(60, 60));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setPreferredSize(new java.awt.Dimension(60, 60));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setPreferredSize(new java.awt.Dimension(60, 60));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setPreferredSize(new java.awt.Dimension(60, 60));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setPreferredSize(new java.awt.Dimension(60, 60));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setPreferredSize(new java.awt.Dimension(60, 60));
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn4.setPreferredSize(new java.awt.Dimension(60, 60));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn8.setPreferredSize(new java.awt.Dimension(60, 60));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn12.setPreferredSize(new java.awt.Dimension(60, 60));
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn15.setPreferredSize(new java.awt.Dimension(60, 60));
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setPreferredSize(new java.awt.Dimension(60, 60));
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn13.setPreferredSize(new java.awt.Dimension(60, 60));
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.setPreferredSize(new java.awt.Dimension(60, 60));
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn3x3Layout = new javax.swing.GroupLayout(pn3x3);
        pn3x3.setLayout(pn3x3Layout);
        pn3x3Layout.setHorizontalGroup(
            pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn3x3Layout.setVerticalGroup(
            pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3x3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn3x3Layout.createSequentialGroup()
                        .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn3x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        jLabel1.setText("Move count: ");

        jLabel2.setText("Elapsed: ");

        jLabel3.setText("Size: ");

        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "4x4" }));
        cboSize.setSelectedIndex(1);
        cboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSizeActionPerformed(evt);
            }
        });

        lbMoveCount.setText("0");

        lbElapsed.setText("0 sec");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMoveCount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbElapsed, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnNewGame)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn3x3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbMoveCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbElapsed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn1.getText());
            btn1.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn5.getText() == "") {
            btn5.setText(btn1.getText());
            btn1.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        makeNewGame();
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText() == "") {
            btn1.setText(btn2.getText());
            btn2.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn3.getText() == "") {
            btn3.setText(btn2.getText());
            btn2.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn6.getText() == "") {
            btn6.setText(btn2.getText());
            btn2.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn3.getText());
            btn3.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn4.getText() == "") {
            btn4.setText(btn3.getText());
            btn3.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn7.getText() == "") {
            btn7.setText(btn3.getText());
            btn3.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (btn5.getText() == "") {
            btn5.setText(btn9.getText());
            btn9.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn10.getText() == "") {
            btn10.setText(btn9.getText());
            btn9.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn13.getText() == "") {
            btn13.setText(btn9.getText());
            btn9.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if (btn7.getText() == "") {
            btn7.setText(btn11.getText());
            btn11.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn10.getText() == "") {
            btn10.setText(btn11.getText());
            btn11.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn12.getText() == "") {
            btn12.setText(btn11.getText());
            btn11.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn15.getText() == "") {
            btn15.setText(btn11.getText());
            btn11.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn1.getText() == "") {
            btn1.setText(btn5.getText());
            btn5.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn6.getText() == "") {
            btn6.setText(btn5.getText());
            btn5.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn9.getText() == "") {
            btn9.setText(btn5.getText());
            btn5.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText() == "") {
            btn3.setText(btn7.getText());
            btn7.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn6.getText() == "") {
            btn6.setText(btn7.getText());
            btn7.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn8.getText() == "") {
            btn8.setText(btn7.getText());
            btn7.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn11.getText() == "") {
            btn11.setText(btn7.getText());
            btn7.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        if (btn6.getText() == "") {
            btn6.setText(btn10.getText());
            btn10.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn9.getText() == "") {
            btn9.setText(btn10.getText());
            btn10.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn11.getText() == "") {
            btn11.setText(btn10.getText());
            btn10.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn14.getText() == "") {
            btn14.setText(btn10.getText());
            btn10.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn2.getText() == "") {
            btn2.setText(btn6.getText());
            btn6.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn5.getText() == "") {
            btn5.setText(btn6.getText());
            btn6.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn7.getText() == "") {
            btn7.setText(btn6.getText());
            btn6.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn10.getText() == "") {
            btn10.setText(btn6.getText());
            btn6.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn3.getText() == "") {
            btn3.setText(btn4.getText());
            btn4.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn8.getText() == "") {
            btn8.setText(btn4.getText());
            btn4.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void cboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSizeActionPerformed
        // TODO add your handling code here:
        if (cboSize.getSelectedIndex() == 0) {
            JFrame frame = new NPG();
            frame.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cboSizeActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (btn4.getText() == "") {
            btn4.setText(btn8.getText());
            btn8.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn7.getText() == "") {
            btn7.setText(btn8.getText());
            btn8.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn12.getText() == "") {
            btn12.setText(btn8.getText());
            btn8.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        if (btn8.getText() == "") {
            btn8.setText(btn12.getText());
            btn12.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn11.getText() == "") {
            btn11.setText(btn12.getText());
            btn12.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn16.getText() == "") {
            btn16.setText(btn12.getText());
            btn12.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        if (btn9.getText() == "") {
            btn9.setText(btn13.getText());
            btn13.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn14.getText() == "") {
            btn14.setText(btn13.getText());
            btn13.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        if (btn10.getText() == "") {
            btn10.setText(btn14.getText());
            btn14.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn13.getText() == "") {
            btn13.setText(btn14.getText());
            btn14.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn15.getText() == "") {
            btn15.setText(btn14.getText());
            btn14.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_btn14ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        if (btn11.getText() == "") {
            btn11.setText(btn15.getText());
            btn15.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn14.getText() == "") {
            btn14.setText(btn15.getText());
            btn15.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn16.getText() == "") {
            btn16.setText(btn15.getText());
            btn15.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        if (btn12.getText() == "") {
            btn12.setText(btn16.getText());
            btn16.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (btn15.getText() == "") {
            btn15.setText(btn16.getText());
            btn16.setText("");
            lbMoveCount.setText(String.valueOf(moveCount++));
        }
        if (validWin()) {
            int choice = JOptionPane.showConfirmDialog(this, "You win!~ Do you want play again?", "NPG", JOptionPane.YES_NO_OPTION);
            if (choice == 0) {
                makeNewGame();
            } else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btn16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NPG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NPG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NPG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NPG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NPG2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbElapsed;
    private javax.swing.JLabel lbMoveCount;
    private javax.swing.JPanel pn3x3;
    // End of variables declaration//GEN-END:variables
}
